### ISSUE TITLE
Problems with Stackage nightly

### ISSUE THREAD

**Issue by serras** [haskell-grpc-native/http2-grpc-haskell#13]
If one tries to add our packages to Stackage, it is welcomed with the following errors:

```
    bytestring version 0.10.9.0 found
        - http2-client-grpc requires >=0.10.8 && <0.10.9
    http2 version 2.0.3 found
        - http2-client requires >=1.6 && <2
        - http2-client-grpc requires >=1.6 && <1.7
    http2-grpc-types version 0.4.0.0 found
        - warp-grpc requires >=0.5 && <0.6
    lens version 4.18.1 found
        - http2-client-grpc requires >=4.16 && <4.18
    network version 3.1.1.0 found
        - http2-client requires >=2.6 && <3
    proto-lens version 0.6.0.0 found
        - http2-client-grpc requires >=0.5 && <0.6
        - http2-grpc-types requires >=0.5 && <0.6
    tls version 1.5.2 found
        - http2-client-grpc requires >=1.4 && <1.5
    warp version 3.3.3 found
        - warp-grpc requires >=3.2.24 && <3.3
```

We need to loosen the bounds to allow the programs to compile in newer versions.

**Comment by lucasdicioccio** [comment]
Looks like it's feasible with little risk. I know most of the dependencies pretty well, so if problems occur I can likely find workarounds.

I'll have some time Sunday/Monday (thought, I'd like to start bringing back the example packages and port them to proto3-wire -- it will serve a good basis for compatibility-tests).

**Comment by serras** [comment]
The main problem would be convincing the proto3-wire maintainers to upload
a new version which build with hashable >= 1.3.

**Comment by lucasdicioccio** [comment]
I could build with today's nightly and `proto3-wire-1.1.0`
