### ISSUE TITLE
Try loosening the bound on `base` to support older GHC versions.

### ISSUE THREAD

**Issue by lucasdicioccio** [haskell-grpc-native/http2-grpc-haskell#3]
This issue is a fork of https://github.com/lucasdicioccio/http2-grpc-types/issues/1

**Comment by serras** [comment]
Maybe we can try to support different Stackage LTSs? Doing so using Travis CI is quite simple.

**Comment by lucasdicioccio** [comment]
That's definitely a good idea, yes.

Regarding backward compatibility, at some point I think we'll want to run some periodic survey from existing and would-be users to calibrate well effort vs. usefulness. Thus, it's a bit premature at this stage to commit on anything.

Fortunately our libs are hopefully small enough :-).

**Comment by serras** [comment]
In theory, it should be easy to test different versions by using different Stackage LTS releases. I'll try to add LTS 12 (for GHC 8.4.4 and base 4.11) to CI too.

**Comment by serras** [comment]
I have now added support for LTS 11 too (#14), so I think we support a broad enough range of versions (8.2, 8.4, 8.6, 8.8).
