### ISSUE TITLE
include .cabal file in http2-grpc-types package

### ISSUE THREAD

**Issue by blinky3713** [haskell-grpc-native/http2-grpc-haskell#41]
https://github.com/commercialhaskell/stack/issues/5210

I'm currently getting a warning that future versions of stack will not support building this dependency without a cabal file

**Comment by ethercrow** [comment]
With cabal it's even an error, not a warning.

When I have this in a `cabal.project`:

```
source-repository-package
  type: git
  location: https://github.com/haskell-grpc-native/http2-grpc-haskell
  tag: 496e92bc967eff02ac3698ba12ba2dfe38bc8b74
  subdir: http2-grpc-types
```

cabal says

```
   Cloning into '/home/runner/work/lightstep-haskell/lightstep-haskell/dist-newstyle/src/http2-grp_-decb6024caea4828'...
  HEAD is now at 496e92b Merge pull request #36 from haskell-grpc-native/introduce-bench-tool
  NoCabalFileFound
Error: The process '/opt/cabal/3.0/bin/cabal' failed with exit code 1
```

**Comment by Bargsteen** [comment]
Dealing with the same warning right now, so it would be nice if fixed.

**Comment by ethercrow** [comment]
@lucasdicioccio please have a look.

**Comment by lucasdicioccio** [comment]
Hi, thanks for the highlight; it looks like I don't get emails notifications for this project now that we've moved it to an organization. And suddently I feel ashamed to let this linger for so long. Will have a look very soon

**Comment by lucasdicioccio** [comment]
Can someone have a quick look at #43 ?

**Comment by lucasdicioccio** [comment]
Feel free to reopen and @ mention me :pray: . I've turned the "Watch" bit to make sure such horrible delays don't occur again (modulo :baby: induced exhaustion).

**Comment by Bargsteen** [comment]
> Can someone have a quick look at #43 ?

The warning is now gone. Thanks!
