### ISSUE TITLE
Support unix sockets in http2-client-grpc

### ISSUE THREAD

**Issue by akshaymankar** [haskell-grpc-native/http2-grpc-haskell#42]
The [`GrpcClientConfig`](https://github.com/haskell-grpc-native/http2-grpc-haskell/blob/496e92bc967eff02ac3698ba12ba2dfe38bc8b74/http2-client-grpc/src/Network/GRPC/Client/Helpers.hs#L65-L86) only allows connection by `Hostname` and `PortNumber`. It would be nice if it somehow supported Unix sockets too. Additionally, an option to take `Network.Socket` would be nice too.

**Comment by lucasdicioccio** [comment]
Do you mind trying a patch for this one?

Wondering between:
- (a) parsing a URL
- (b) asking a sum-type as input
- (c) asking a socket

Not a big fan of (c) because this API is intended for typical cases where a user prefers to trust us on initializing all the boilerplate.

**Comment by akshaymankar** [comment]
I had a fork on which I was working, I just created a PR from that here: #44.
